server:
  port: 4000
spring:
  application:
    name: wzf-crowd-auth
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false 
  redis:
    host: 192.168.124.23
    port: 6379
  session:
    store-type: redis
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
short:
  message:
    host: https://smssend.shumaidata.com
    path: /sms/send
    method: POST
    appcode: 33799400e7f64d9f9b8a85fd07eb3f05
    template-id: M09DD535F4
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
    