server:
  port: 80
spring:
  application:
    name: wzf-crowd-zuul
  session:
    store-type: redis
  redis:
    host: 192.168.124.23
    port: 6379
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
zuul:
  ignored-services: "*"
  sensitive-headers: "*" # 在 Zuul 向其他微服务重定向时保持原本头信息（请求头、响应头）
  routes:
    crowd-portal:
      service-id: wzf-crowd-auth
      path: /** # 这里一定要使用两个“*”号，不然“/”路径后面的多层路径将无法访问      
    crowd-project:
      service-id: wzf-crowd-project
      path: /project/**

ribbon:
  ReadTimeout: 10000  #请求处理的超时时间
  ConnectTimeout: 10000  #请求连接的超时时间
      